Repository AY1920S2-CS2103T-W12-2/main, pull requests merged in 2020-04, with the labels that each got.

#124 Added error handling for admin fetch and admin delete. [Do not merge]
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/parser/AdminCommandParser.java
  src/main/java/seedu/address/model/admin/UniqueDateList.java
  src/main/java/seedu/address/model/admin/exceptions/DateNotFoundException.java
  src/main/java/seedu/address/model/admin/exceptions/DuplicateDateException.java
  src/main/java/seedu/address/ui/CommandBox.java
  src/main/java/seedu/address/ui/MainWindow.java
Labels: priority.High, severity.High, status.Complete, type.Bug, type.UI

#118 Academics Feature
  docs/team/tingalinga.html
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/academics/AcademicsAddCommand.java
  src/main/java/seedu/address/logic/commands/academics/AcademicsCommand.java
  src/main/java/seedu/address/logic/commands/academics/AcademicsSubmitCommand.java
  src/main/java/seedu/address/logic/commands/academics/display/AcademicsDisplayCommand.java
  src/main/java/seedu/address/logic/commands/academics/display/AcademicsDisplayExamCommand.java
  src/main/java/seedu/address/logic/commands/academics/display/AcademicsDisplayHomeworkCommand.java
  src/main/java/seedu/address/logic/commands/academics/display/AcademicsDisplayStatisticsCommand.java
  src/main/java/seedu/address/logic/commands/notes/NotesDeleteCommand.java
  src/main/java/seedu/address/logic/parser/AcademicsCommandParser.java
  src/main/java/seedu/address/logic/parser/ArgumentMultimap.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/TeaPetParser.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/academics/Academics.java
  src/main/java/seedu/address/model/academics/Assessment.java
  src/main/java/seedu/address/model/academics/Exam.java
  src/main/java/seedu/address/model/academics/Homework.java
  src/main/java/seedu/address/model/academics/ReadOnlyAcademics.java
  src/main/java/seedu/address/model/academics/UniqueAssessmentList.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/Storage.java
  src/main/java/seedu/address/storage/StorageManager.java
  src/main/java/seedu/address/storage/academics/AcademicsStorage.java
  src/main/java/seedu/address/storage/academics/JsonAcademicsStorage.java
  src/main/java/seedu/address/storage/academics/JsonAdaptedAssessment.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/NotesCard.java
  src/main/java/seedu/address/ui/NotesPanel.java
  src/main/java/seedu/address/ui/academics/AcademicsPanel.java
  src/main/java/seedu/address/ui/academics/AssessmentCard.java
  src/main/java/seedu/address/ui/academics/AssessmentCardExam.java
  src/main/java/seedu/address/ui/academics/AssessmentCardHomework.java
  src/main/java/seedu/address/ui/academics/AssessmentCardStatistics.java
  src/main/resources/view/AcademicsPanel.fxml
  src/main/resources/view/AssessmentCard.fxml
  src/main/resources/view/AssessmentCardExam.fxml
  src/main/resources/view/AssessmentCardHomework.fxml
  src/main/resources/view/AssessmentCardStatistics.fxml
  src/main/resources/view/MainWindow.fxml
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/storage/StorageManagerTest.java
Labels: priority.High, status.Ongoing, type.UI

#126 Added Date list ui and made other logical changes of finding students and dates.
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/logic/commands/admin/AdminCommand.java
  src/main/java/seedu/address/logic/commands/admin/AdminDatesCommand.java
  src/main/java/seedu/address/logic/commands/admin/AdminDeleteCommand.java
  src/main/java/seedu/address/logic/commands/admin/AdminFetchCommand.java
  src/main/java/seedu/address/logic/commands/studentdisplay/DefaultStudentDisplayCommand.java
  src/main/java/seedu/address/logic/commands/studentdisplay/DetailedStudentDisplayCommand.java
  src/main/java/seedu/address/logic/parser/AdminCommandParser.java
  src/main/java/seedu/address/model/student/exceptions/StudentNotFoundException.java
  src/main/java/seedu/address/ui/CommandBox.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/StudentListPanel.java
  src/main/java/seedu/address/ui/admin/DateCard.java
  src/main/java/seedu/address/ui/admin/DateListPanel.java
  src/main/resources/view/DateListCard.fxml
  src/main/resources/view/DateListPanel.fxml
  src/test/java/seedu/address/logic/commands/FindCommandTest.java
Labels: priority.High, status.Complete

#122 added intro to developer guide and minor changes to user guide
  docs/DeveloperGuide.adoc
  docs/SettingUp.adoc
  docs/UserGuide.adoc
Labels: priority.High, status.Ongoing, type.DevGuide

#125 Notes Feature Updates [DO NOT MERGE]
  docs/UserGuide.adoc
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/RemarkCommand.java
  src/main/java/seedu/address/logic/commands/notes/NotesAddCommand.java
  src/main/java/seedu/address/logic/commands/notes/NotesCommand.java
  src/main/java/seedu/address/logic/commands/notes/NotesDeleteCommand.java
  src/main/java/seedu/address/logic/commands/notes/NotesExportCommand.java
  src/main/java/seedu/address/logic/commands/notes/NotesFilterCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/TeaPetParser.java
  src/main/java/seedu/address/logic/parser/notes/NotesAddCommandParser.java
  src/main/java/seedu/address/logic/parser/notes/NotesCommandParser.java
  src/main/java/seedu/address/logic/parser/notes/NotesExportCommandParser.java
  src/main/java/seedu/address/model/notes/Notes.java
  src/main/java/seedu/address/model/notes/NotesContainKeywordsPredicate.java
  src/main/java/seedu/address/model/notes/NotesManager.java
  src/main/java/seedu/address/model/student/Student.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedNotes.java
  src/main/java/seedu/address/storage/JsonAdaptedStudent.java
  src/main/java/seedu/address/storage/notes/JsonAdaptedNotes.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/NotesCard.java
  src/main/java/seedu/address/ui/NotesExporter.java
  src/main/java/seedu/address/ui/StudentCard.java
  src/main/java/seedu/address/ui/StudentCardDetailed.java
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/NotesCard.fxml
  src/main/resources/view/NotesPanel.fxml
  src/main/resources/view/ScheduleWindow.fxml
  src/main/resources/view/StudentListCard.fxml
  src/main/resources/view/StudentListCardDetailed.fxml
  src/main/resources/view/TempTheme.css
  src/test/java/seedu/address/model/notes/NotesTest.java
  src/test/java/seedu/address/storage/JsonAdaptedNotesTest.java
  src/test/java/seedu/address/storage/JsonAdaptedStudentTest.java
  src/test/java/seedu/address/testutil/StudentBuilder.java
  src/test/java/seedu/address/testutil/TypicalNotes.java
Labels: priority.High, status.Ongoing

#128 fix minor bug in developer guide and event add command [DO NOT MERGE]
  docs/DeveloperGuide.adoc
  src/main/java/seedu/address/logic/commands/event/EventAddCommand.java
Labels: priority.High, severity.High, status.Ongoing

#129 added view schedule
  src/main/java/seedu/address/logic/commands/event/EventAddCommand.java
  src/main/java/seedu/address/logic/commands/event/EventCommand.java
  src/main/java/seedu/address/logic/commands/event/EventDisplayCommand.java
  src/main/java/seedu/address/logic/parser/EventCommandParser.java
  src/main/java/seedu/address/ui/HelpWindow.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/SchedulePage.java
  src/main/resources/view/HelpWindow.fxml
  src/main/resources/view/SchedulePanel.fxml
Labels: priority.High, severity.High, status.Complete, type.Task

#131 minor updates to beautify user guide
  docs/UserGuide.adoc
Labels: priority.High, status.Complete, type.UserGuide

#212 removed list from helpwiwndow
  src/main/java/seedu/address/ui/HelpWindow.java
Labels: priority.High, severity.High, type.UserGuide

#215 Notes Feature Updates [DO NOT MERGE]
  images/freddyzhang.png
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/notes/NotesAddCommand.java
  src/main/java/seedu/address/logic/commands/notes/NotesEditCommand.java
  src/main/java/seedu/address/logic/commands/notes/NotesExportCommand.java
  src/main/java/seedu/address/logic/parser/TeaPetParser.java
  src/main/java/seedu/address/logic/parser/notes/NotesEditCommandParser.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/resources/view/TempTheme.css
Labels: priority.High, status.Ongoing

#219 improved schedule function [DO NOT MERGE]
  build.gradle
  docs/tutorials/AddRemark.adoc
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/commons/util/EventUtil.java
  src/main/java/seedu/address/commons/util/StringUtil.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/RemarkCommand.java
  src/main/java/seedu/address/logic/commands/academics/AcademicsDeleteCommand.java
  src/main/java/seedu/address/logic/commands/event/EventAddCommand.java
  src/main/java/seedu/address/logic/commands/event/EventDeleteCommand.java
  src/main/java/seedu/address/logic/commands/event/EventEditCommand.java
  src/main/java/seedu/address/logic/commands/event/EventIndexCommand.java
  src/main/java/seedu/address/logic/commands/event/EventViewCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/EventCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/RemarkCommandParser.java
  src/main/java/seedu/address/logic/parser/TeaPetParser.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/event/EventHistory.java
  src/main/java/seedu/address/model/event/exceptions/VEventNotFoundException.java
  src/main/java/seedu/address/model/student/Remark.java
  src/main/java/seedu/address/model/student/Student.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedStudent.java
  src/main/java/seedu/address/ui/HelpWindow.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/SchedulePanel.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/RemarkCommandTest.java
  src/test/java/seedu/address/storage/JsonAdaptedStudentTest.java
  src/test/java/seedu/address/testutil/StudentBuilder.java
  src/test/java/seedu/address/testutil/TypicalStudents.java
Labels: priority.High, severity.High, status.Complete, type.Enhancement, type.Task

#227 Implemented WebView API and changed help window
  build.gradle
  src/main/java/seedu/address/ui/HelpWindow.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/resources/view/HelpWindow.fxml
Labels: priority.Medium, status.Ongoing, type.Task, type.UI

#238 Added some test cases to increase coverall
  src/main/java/seedu/address/commons/util/EventUtil.java
  src/main/java/seedu/address/logic/commands/event/EventViewCommand.java
  src/main/java/seedu/address/model/event/EventHistory.java
  src/test/java/seedu/address/logic/commands/event/EventAddCommandTest.java
  src/test/java/seedu/address/model/event/EventHistoryTest.java
  src/test/java/seedu/address/model/event/EventTest.java
  src/test/java/seedu/address/testutil/ModelStub.java
  src/test/java/seedu/address/testutil/event/ModelStubWithVEvent.java
Labels: priority.High, status.Ongoing, type.Task

#262 RE: [PE-D] Date format for adding event for schedule can be specified
  docs/UserGuide.adoc
  src/main/java/seedu/address/commons/util/EventUtil.java
Labels: priority.High, severity.High, status.Ongoing, type.Bug

#269 improved schedule functions
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/commons/util/EventUtil.java
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/event/EventAddCommand.java
  src/main/java/seedu/address/logic/commands/event/EventDeleteCommand.java
  src/main/java/seedu/address/logic/commands/event/EventDisplayCommand.java
  src/main/java/seedu/address/logic/commands/event/EventEditCommand.java
  src/main/java/seedu/address/logic/commands/event/EventExportCommand.java
  src/main/java/seedu/address/logic/commands/event/EventIndexAllCommand.java
  src/main/java/seedu/address/logic/commands/event/EventIndexCommand.java
  src/main/java/seedu/address/logic/commands/event/EventViewCommand.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/EventCommandParser.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/event/EventHistory.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/event/EventExporter.java
  src/test/java/seedu/address/logic/commands/StudentAddCommandTest.java
  src/test/java/seedu/address/logic/commands/notes/NotesAddCommandTest.java
  src/test/java/seedu/address/testutil/ModelStub.java
Labels: priority.High, severity.High, type.Task

#281 added schedule tests
  docs/team/garysyndromes.adoc
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/commons/util/EventUtil.java
  src/main/java/seedu/address/logic/commands/event/EventIndexAllCommand.java
  src/main/java/seedu/address/logic/commands/event/EventIndexCommand.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/event/EventHistory.java
  src/test/java/seedu/address/commons/util/EventUtilTest.java
  src/test/java/seedu/address/logic/commands/event/EventDeleteCommandTest.java
  src/test/java/seedu/address/logic/commands/event/EventDisplayCommandTest.java
  src/test/java/seedu/address/logic/commands/event/EventEditCommandTest.java
  src/test/java/seedu/address/logic/commands/event/EventExportCommandTest.java
  src/test/java/seedu/address/logic/commands/event/EventIndexAllCommandTest.java
  src/test/java/seedu/address/logic/commands/event/EventIndexCommandTest.java
  src/test/java/seedu/address/logic/commands/event/EventViewCommandTest.java
  src/test/java/seedu/address/logic/commands/notes/NotesAddCommandTest.java
  src/test/java/seedu/address/logic/commands/student/StudentAddCommandTest.java
  src/test/java/seedu/address/logic/parser/EventCommandParserTest.java
  src/test/java/seedu/address/testutil/ModelStub.java
  src/test/java/seedu/address/testutil/TypicalIndexes.java
  src/test/java/seedu/address/testutil/event/TypicalVEvents.java
Labels: priority.High, severity.High, type.Test

#285 updated ug for personal schedule
  docs/UserGuide.adoc
  docs/team/garysyndromes.adoc
Labels: priority.High, severity.High, type.UserGuide
