Repository AY1920S2-CS2103T-W12-2/main, pull requests merged in 2020-03, with the labels that each got.

#62 Added product survey
  docs/DeveloperGuide.adoc
Labels: priority.Medium, type.Enhancement

#61 Lower argument limitations on add command
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/ArgumentMultimap.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/student/Email.java
  src/main/java/seedu/address/model/student/Phone.java
  src/main/java/seedu/address/model/student/Student.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/StudentCard.java
  src/main/resources/view/StudentListCard.fxml
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ArgumentTokenizerTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/model/student/PhoneTest.java
Labels: priority.Medium, type.Task

#66 Add temperature
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/RemarkCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/ArgumentMultimap.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/student/Phone.java
  src/main/java/seedu/address/model/student/Student.java
  src/main/java/seedu/address/model/student/Temperature.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedStudent.java
  src/main/java/seedu/address/ui/StudentCard.java
  src/main/resources/view/StudentListCard.fxml
  src/test/data/JsonAddressBookStorageTest/invalidAndValidStudentAddressBook.json
  src/test/data/JsonAddressBookStorageTest/invalidStudentAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/duplicateStudentAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/invalidStudentAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalStudentsAddressBook.json
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ArgumentTokenizerTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/model/student/TemperatureTest.java
  src/test/java/seedu/address/storage/JsonAdaptedStudentTest.java
  src/test/java/seedu/address/testutil/EditStudentDescriptorBuilder.java
  src/test/java/seedu/address/testutil/StudentBuilder.java
  src/test/java/seedu/address/testutil/StudentUtil.java
  src/test/java/seedu/address/testutil/TypicalStudents.java
Labels: priority.High, type.Task

#67 Implement class progress management
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/model/homework/Homework.java
  src/main/java/seedu/address/ui/UiManager.java
  src/main/resources/images/teapot_icon.png
  src/main/resources/view/CommandBox.fxml
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/MainWindow.fxml
Labels: priority.High, type.Task

#65 Implemented NOK attributes to student
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/RemarkCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/ArgumentMultimap.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/student/NextOfKin.java
  src/main/java/seedu/address/model/student/Student.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedStudent.java
  src/main/java/seedu/address/ui/StudentCard.java
  src/main/resources/view/StudentListCard.fxml
  src/test/data/JsonSerializableAddressBookTest/duplicateStudentAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalStudentsAddressBook.json
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/model/student/NextOfKinTest.java
  src/test/java/seedu/address/storage/JsonAdaptedStudentTest.java
  src/test/java/seedu/address/testutil/StudentBuilder.java
  src/test/java/seedu/address/testutil/TypicalStudents.java
Labels: priority.High, type.Task

#79 Changed style of editing students such that only the attributes to ed…
  src/main/java/seedu/address/logic/parser/ArgumentMultimap.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
Labels: priority.High, severity.High, status.Complete

#78 Adding default image to each student
  src/main/java/seedu/address/ui/StudentCard.java
  src/main/resources/images/default_image.png
  src/main/resources/view/StudentListCard.fxml
Labels: priority.Medium, status.Ongoing, type.Task

#81 added help window
  src/main/java/seedu/address/ui/HelpWindow.java
  src/main/resources/view/HelpWindow.fxml
Labels: priority.High, severity.High, status.Complete, type.UI

#77 Intermediate Level Implementation of Class Progress Management Feature
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/AcademicsAddCommand.java
  src/main/java/seedu/address/logic/commands/AcademicsCommand.java
  src/main/java/seedu/address/logic/parser/AcademicsCommandParser.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/ArgumentMultimap.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/Parser.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/academics/Academics.java
  src/main/java/seedu/address/model/academics/Assessment.java
  src/main/java/seedu/address/model/academics/Exam.java
  src/main/java/seedu/address/model/academics/Homework.java
  src/main/java/seedu/address/model/academics/ReadOnlyAcademics.java
  src/main/java/seedu/address/model/academics/SavedAcademics.java
  src/main/java/seedu/address/model/academics/Submission.java
  src/main/java/seedu/address/model/academics/exceptions/AssessmentNotFoundException.java
  src/main/java/seedu/address/model/academics/exceptions/DuplicateAssessmentException.java
  src/main/java/seedu/address/model/homework/Homework.java
Labels: priority.High, severity.High, status.Ongoing

#89 Add attendance
  src/main/java/seedu/address/logic/commands/AcademicsAddCommand.java
  src/main/java/seedu/address/logic/commands/AcademicsCommand.java
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/RemarkCommand.java
  src/main/java/seedu/address/logic/commands/notes/AdminNotesCommand.java
  src/main/java/seedu/address/logic/parser/AcademicsCommandParser.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/ArgumentMultimap.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/academics/Academics.java
  src/main/java/seedu/address/model/academics/Assessment.java
  src/main/java/seedu/address/model/academics/Exam.java
  src/main/java/seedu/address/model/academics/Homework.java
  src/main/java/seedu/address/model/academics/ReadOnlyAcademics.java
  src/main/java/seedu/address/model/academics/SavedAcademics.java
  src/main/java/seedu/address/model/academics/Submission.java
  src/main/java/seedu/address/model/student/Attendance.java
  src/main/java/seedu/address/model/student/Student.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedStudent.java
  src/main/java/seedu/address/ui/HelpWindow.java
  src/main/java/seedu/address/ui/StudentCardDetailed.java
  src/main/resources/view/StudentListCardDetailed.fxml
  src/test/data/JsonSerializableAddressBookTest/duplicateStudentAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/invalidStudentAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalStudentsAddressBook.json
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/CommandParserTestUtil.java
  src/test/java/seedu/address/model/student/AttendanceTest.java
  src/test/java/seedu/address/model/student/StudentTest.java
  src/test/java/seedu/address/storage/JsonAdaptedStudentTest.java
  src/test/java/seedu/address/storage/JsonSerializableAddressBookTest.java
  src/test/java/seedu/address/testutil/EditStudentDescriptorBuilder.java
  src/test/java/seedu/address/testutil/StudentBuilder.java
  src/test/java/seedu/address/testutil/StudentUtil.java
  src/test/java/seedu/address/testutil/TypicalStudents.java
Labels: priority.High, severity.High, status.Complete, type.UI

#96 Image update
  images/gerrenseow.png
  images/simonlam.png
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/ui/StudentCard.java
  src/main/java/seedu/address/ui/StudentCardAdmin.java
  src/main/java/seedu/address/ui/StudentCardDetailed.java
  src/main/resources/images/default_image.png
  src/main/resources/view/StudentListCard.fxml
  src/main/resources/view/StudentListCardAdmin.fxml
  src/main/resources/view/StudentListCardDetailed.fxml
Labels: priority.High, status.Complete, type.Task, type.UI

#99 Minor refactors and DG inputs
  docs/DeveloperGuide.adoc
  docs/diagrams/DeleteSequenceDiagram.puml
  docs/diagrams/LogicClassDiagram.puml
  docs/diagrams/ModelClassDiagram.puml
  docs/diagrams/StorageClassDiagram.puml
  docs/images/DeleteSequenceDiagram.png
  docs/images/LogicClassDiagram.png
  docs/images/ModelClassDiagram.png
  docs/images/StorageClassDiagram.png
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/parser/TeaPetParser.java
  src/test/java/seedu/address/logic/parser/TeaPetParserTest.java
Labels: priority.High, status.Complete, type.DevGuide, type.Task

#100 Added new UML class diagram for commands
  docs/DeveloperGuide.adoc
  docs/images/CommandClassDiagram.png
Labels: priority.High, status.Complete, type.DevGuide, type.Enhancement

#101 Added refresh function
  docs/DeveloperGuide.adoc
  images/garysyndromes.png
  images/leehuiting.png
  src/main/java/seedu/address/logic/commands/RefreshCommand.java
  src/main/java/seedu/address/logic/parser/TeaPetParser.java
  src/main/java/seedu/address/ui/StudentCard.java
  src/main/java/seedu/address/ui/StudentListPanel.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/RefreshCommandTest.java
  src/test/java/seedu/address/logic/parser/TeaPetParserTest.java
Labels: priority.High, status.Complete, type.Bug

#104 Sequence diagram
  docs/DeveloperGuide.adoc
  docs/diagrams/AddSequenceDiagram.puml
  docs/images/AddSequenceDiagram.png
Labels: priority.High, type.DevGuide

#103 Implement class progress management storage
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/AcademicsAddCommand.java
  src/main/java/seedu/address/logic/commands/AcademicsCommand.java
  src/main/java/seedu/address/logic/parser/AcademicsCommandParser.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/ReadOnlyUserPrefs.java
  src/main/java/seedu/address/model/UserPrefs.java
  src/main/java/seedu/address/model/academics/Academics.java
  src/main/java/seedu/address/model/academics/Assessment.java
  src/main/java/seedu/address/model/academics/Exam.java
  src/main/java/seedu/address/model/academics/Homework.java
  src/main/java/seedu/address/model/academics/SavedAcademics.java
  src/main/java/seedu/address/model/academics/Submission.java
  src/main/java/seedu/address/model/academics/UniqueAssessmentList.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/Storage.java
  src/main/java/seedu/address/storage/StorageManager.java
  src/main/java/seedu/address/storage/academics/AcademicsStorage.java
  src/main/java/seedu/address/storage/academics/JsonAcademicsStorage.java
  src/main/java/seedu/address/storage/academics/JsonAdaptedAssessment.java
  src/main/java/seedu/address/storage/academics/JsonAdaptedSubmission.java
  src/main/java/seedu/address/storage/academics/JsonSerializableAcademics.java
  src/main/java/seedu/address/ui/HelpWindow.java
Labels: priority.High, severity.High, status.Ongoing

#112 updated user guide
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
Labels: status.Complete, type.UserGuide

#108 Implementation of scheduler [DO NOT MERGE]
  build.gradle
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/commons/util/EventUtil.java
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/CommandResult.java
  src/main/java/seedu/address/logic/commands/event/EventAddCommand.java
  src/main/java/seedu/address/logic/commands/event/EventCommand.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/EventCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/TeaPetParser.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/UserPrefs.java
  src/main/java/seedu/address/model/event/Event.java
  src/main/java/seedu/address/model/event/EventHistory.java
  src/main/java/seedu/address/model/event/EventSchedulePrefs.java
  src/main/java/seedu/address/model/event/EventScheduleView.java
  src/main/java/seedu/address/model/event/ReadOnlyEvents.java
  src/main/java/seedu/address/model/event/ReadOnlyVEvents.java
  src/main/java/seedu/address/model/event/RecurrenceType.java
  src/main/java/seedu/address/model/event/exceptions/DuplicateVEventException.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/Storage.java
  src/main/java/seedu/address/storage/StorageManager.java
  src/main/java/seedu/address/storage/event/EventStorage.java
  src/main/java/seedu/address/storage/event/JsonAdaptedEvent.java
  src/main/java/seedu/address/storage/event/JsonEventStorage.java
  src/main/java/seedu/address/storage/event/JsonSerializableEvents.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/SchedulePanel.java
  src/main/java/seedu/address/ui/ScheduleWindow.java
  src/main/java/seedu/address/ui/UiPart.java
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/SchedulePanel.fxml
  src/main/resources/view/ScheduleWindow.fxml
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/AddCommandIntegrationTest.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/ClearCommandTest.java
  src/test/java/seedu/address/logic/commands/DeleteCommandTest.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/commands/FindCommandTest.java
  src/test/java/seedu/address/logic/commands/RefreshCommandTest.java
  src/test/java/seedu/address/logic/commands/RemarkCommandTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/storage/StorageManagerTest.java
  src/test/java/seedu/address/testutil/event/EventBuilder.java
  src/test/java/seedu/address/testutil/event/TypicalEvents.java
  src/test/java/seedu/address/testutil/event/TypicalVEvents.java
Labels: priority.High, status.Complete
